_PBuilder.init({
	'properties':{
		'global_source':'github', /* localhost, github */
		'global_upload':'github', /* localhost, github */
		'page_title':'Relu person',
		'page_slug':'relu-person',
		'boilerplate':'relu-person',
		'components_path':'relu-org/ArthurWellesleyComponents/', /* organisation/repo */
		'css_source':'relu-org/ArthurWellesleyCSSconcept/', /* organisation/repo */
		'css_structure':'abrahamlincoln',
		'css_dimensions':'abrahamlincoln',
		'css_visual':'abrahamlincoln'
	},
	'schema':{
		's1':{							
			'default_component':'block-img-title-content',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's2':{
			'default_component':'block-title-h2',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's3':{
			'default_component':'block-img',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's4':{
			'default_component':'block-title-h2',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's5':{
			'default_component':'block-img',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's6':{
			'default_component':'block-title-content',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's7':{
			'default_component':'block-title-content',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		}
	}
});